name: Run and create webhook

on:
   pull_request:
    branches:
      - "main"
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"
      - ".github/workflows/development.yml"
      - ".github/workflows/clean.yml"
    types: [opened, synchronize, reopened, labeled]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build app
    steps:
      - uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-  

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Verify dependencies
        run: go mod verify

      - name: Build app
        run: go build -o app
        
  deploy:
    name: Deploy on self hosted
    needs: build
    runs-on: [self-hosted, macOS]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Run app
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
            REPO: ${{ github.event.repository.name }}
            OWNER: ${{ github.repository_owner }}
            PRIVATE_ADDRESS: ${{ secrets.PRIVATE_ADDRESS }}
            WEBHOOK_ENDPOINT: ${{ secrets.WEBHOOK_ENDPOINT }}
        run: ./app
  